global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: infoiplitin
  name: hip
  tag: latest

service:
  type: ClusterIP
  port: 8000

config:
  GATEWAY_URL: "https://dev.abdm.gov.in/gateway"
  ABHA_NUMBER_URL: "https://abhasbx.abdm.gov.in/abha/api"
  ABHA_ADDRESS_URL: "https://phrsbx.abdm.gov.in/api"
  BAHMNI_URL: ""
  GATEWAY_CMSUFFIX: "sbx"
  OTPSERVICE_URL: "http://otp-service:80"
  HIP_URL: "http://hip:8000"
  HEALTH_CHECK_DURATION: 30000
  CORS_ALLOWED_ORIGIN: ""
  CONNECTION_STRING: "Host=bahmni-dev-postgresql;Port=5432;Username=postgres;Password=welcome;Database=hipservice"
  RABBITMQ_HOST: "bahmni-dev-rabbitmq"
  RABBITMQ_USERNAME: "bahmni"
  RABBITMQ_PASSWORD: "bahmni"


secrets:
  GATEWAY_CLIENT_SECRET: ""
  GATEWAY_CLIENT_ID: ""
  OPENMRS_PASSWORD: ""



autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}

