name: Run Code Coverage Check

on:
  push:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core '8.0'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Build with dotnet
        run: dotnet build hip-service.sln
      - name: Run unit tests
        run: dotnet test hip-service.sln
      - name: Set env
        run: echo "name=RELEASE_VERSION::$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
      - name: Test coverage
        run: dotnet test test/In.ProjectEKA.HipServiceTest/In.ProjectEKA.HipServiceTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Publish to Codecov
        run: bash <(curl -s https://codecov.io/bash)  
